# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Field Notes
email: hello@fellowhobbyist.com
description: > # this means to ignore newlines until "baseurl:"
  A collection of notes from a fellow hobbyist working in the
  field of technology.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://fellowhobbyist.com" # the base hostname & protocol for your site
twitter_username: fellowhobbyist
github_username:  fellowhobbyist

# Build settings
markdown: kramdown
